# Generated by Django 3.2.7 on 2021-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(auto_now=True, max_length=128, verbose_name='创建时间'),
        ),
    ]
